export enum WorkspaceDocumentKind {
  RG = 'RG',
  CPF = 'CPF',
  CNH = 'CNH',
  CARTAO_CNPJ = 'CARTAO_CNPJ',
  COMPROVANTE_RESIDENCIA = 'COMPROVANTE_RESIDENCIA',
  CONTRATO_SOCIAL = 'CONTRATO_SOCIAL',
  CONTRATOS_DIVERSOS = 'CONTRATOS_DIVERSOS',
  DOCUMENTOS_DIVERSOS = 'DOCUMENTOS_DIVERSOS',
}
