/**
 * Tipos de documento para arquivo no workspace (PF/PJ — Brasil).
 * Referência ampla: documentos pessoais, fiscais, trabalhistas e empresariais.
 */
export enum WorkspaceDocumentKind {
  // ——— Identificação e civil (PF) ———
  RG = 'RG',
  CPF = 'CPF',
  CNH = 'CNH',
  PASSAPORTE = 'PASSAPORTE',
  CTPS = 'CTPS',
  TITULO_ELEITOR = 'TITULO_ELEITOR',
  CIE_RNE = 'CIE_RNE',
  CRNM = 'CRNM',
  CERTIDAO_NASCIMENTO = 'CERTIDAO_NASCIMENTO',
  CERTIDAO_CASAMENTO = 'CERTIDAO_CASAMENTO',
  CERTIDAO_OBITO = 'CERTIDAO_OBITO',
  // ——— Comprovantes e situação PF ———
  COMPROVANTE_RESIDENCIA = 'COMPROVANTE_RESIDENCIA',
  COMPROVANTE_RENDA = 'COMPROVANTE_RENDA',
  DECLARACAO_IRPF = 'DECLARACAO_IRPF',
  COMPROVANTE_ESCOLARIDADE = 'COMPROVANTE_ESCOLARIDADE',
  COMPROVANTE_CONTA_BANCARIA_PF = 'COMPROVANTE_CONTA_BANCARIA_PF',
  CARTEIRA_ORGAO_CLASSE = 'CARTEIRA_ORGAO_CLASSE',
  COMPROVANTE_INSS = 'COMPROVANTE_INSS',
  FGTS_TRABALHADOR = 'FGTS_TRABALHADOR',
  CONTRATO_TRABALHO = 'CONTRATO_TRABALHO',
  // ——— Poderes, laudos, certidões PF ———
  PROCURACAO = 'PROCURACAO',
  LAUDO_MEDICO_PERICIA = 'LAUDO_MEDICO_PERICIA',
  CERTIDAO_ANTECEDENTES_CRIMINAIS = 'CERTIDAO_ANTECEDENTES_CRIMINAIS',
  CERTIDAO_NADA_CONSTA_JUSTICA = 'CERTIDAO_NADA_CONSTA_JUSTICA',
  // ——— Registro e constituição (PJ) ———
  CARTAO_CNPJ = 'CARTAO_CNPJ',
  CONTRATO_SOCIAL = 'CONTRATO_SOCIAL',
  ATA_CONSTITUICAO = 'ATA_CONSTITUICAO',
  ALTERACAO_CONTRATUAL = 'ALTERACAO_CONTRATUAL',
  ESTATUTO_SOCIAL = 'ESTATUTO_SOCIAL',
  ATA_ASSEMBLEIA_REUNIAO_SOCIOS = 'ATA_ASSEMBLEIA_REUNIAO_SOCIOS',
  CERTIDAO_SIMPLIFICADA_JUNTA = 'CERTIDAO_SIMPLIFICADA_JUNTA',
  CERTIFICADO_MEI = 'CERTIFICADO_MEI',
  // ——— Inscrições, alvarás e licenças (PJ) ———
  INSCRICAO_ESTADUAL = 'INSCRICAO_ESTADUAL',
  INSCRICAO_MUNICIPAL = 'INSCRICAO_MUNICIPAL',
  ALVARA_FUNCIONAMENTO = 'ALVARA_FUNCIONAMENTO',
  LICENCA_AMBIENTAL = 'LICENCA_AMBIENTAL',
  LICENCA_SANITARIA = 'LICENCA_SANITARIA',
  ALVARA_BOMBEIROS = 'ALVARA_BOMBEIROS',
  // ——— Fiscal, contábil e trabalhista (PJ) ———
  BALANCO_PATRIMONIAL = 'BALANCO_PATRIMONIAL',
  DRE_DEMONSTRATIVO = 'DRE_DEMONSTRATIVO',
  DECLARACOES_ACESSORIAS = 'DECLARACOES_ACESSORIAS',
  CERTIDAO_NEGATIVA_DEBITOS_FEDERAL = 'CERTIDAO_NEGATIVA_DEBITOS_FEDERAL',
  CERTIDAO_DEBITOS_TRABALHISTAS = 'CERTIDAO_DEBITOS_TRABALHISTAS',
  CERTIDAO_DEBITOS_MUNICIPAL = 'CERTIDAO_DEBITOS_MUNICIPAL',
  CERTIDAO_DEBITOS_ESTADUAL = 'CERTIDAO_DEBITOS_ESTADUAL',
  // ——— Contratos e operações ———
  CONTRATOS_DIVERSOS = 'CONTRATOS_DIVERSOS',
  CONTRATO_LOCACAO = 'CONTRATO_LOCACAO',
  CONTRATO_FORNECIMENTO = 'CONTRATO_FORNECIMENTO',
  CONTRATO_SERVICOS = 'CONTRATO_SERVICOS',
  CONVENIO_BANCARIO = 'CONVENIO_BANCARIO',
  NOTA_FISCAL = 'NOTA_FISCAL',
  RECIBO_DESPESA = 'RECIBO_DESPESA',
  // ——— Genérico ———
  DOCUMENTOS_DIVERSOS = 'DOCUMENTOS_DIVERSOS',
}
